/**
 * @file    main.c
 * @brief   RaraPLC firmware entry point: HAL bring-up + FreeRTOS scan cycle.
 *
 * Bare FreeRTOS, no OS layer above it. The scan task runs at a fixed period with
 * vTaskDelayUntil: read inputs -> user logic -> execution auditor -> write outputs.
 * Clock tree (SystemClock_Config) and peripheral init come from STM32CubeMX.
 *
 * SPDX-License-Identifier: MIT
 */
#include <stddef.h>
#include "stm32h7xx_hal.h"
#include "FreeRTOS.h"
#include "task.h"

#include "rara_io.h"
#include "rara_encoder.h"

#define RARA_SCAN_PERIOD_MS     10u
#define RARA_SCAN_TASK_PRIO     (configMAX_PRIORITIES - 1)
#define RARA_SCAN_STACK_WORDS   1024u

void SystemClock_Config(void);   /* generated by CubeMX */

static rara_image_t s_image;

static void scan_task(void *arg)
{
    (void)arg;
    TickType_t last = xTaskGetTickCount();

    for (;;) {
        rara_io_read_inputs(&s_image);
        rara_logic_scan(&s_image);

        if (!rara_auditor_check(&s_image)) {
            s_image.dq = 0u;            /* fail safe: all outputs off */
        }

        rara_io_write_outputs(&s_image);
        s_image.scan_count++;

        vTaskDelayUntil(&last, pdMS_TO_TICKS(RARA_SCAN_PERIOD_MS));
    }
}

int main(void)
{
    HAL_Init();
    SystemClock_Config();

    rara_io_init();
    (void)rara_encoder_init(RARA_ENC1, 5u);
    (void)rara_encoder_init(RARA_ENC2, 5u);
    (void)rara_encoder_init(RARA_ENC3, 5u);

    xTaskCreate(scan_task, "scan", RARA_SCAN_STACK_WORDS, NULL, RARA_SCAN_TASK_PRIO, NULL);
    /* Next: comms task (Modbus RTU/TCP, OPC-UA, micro-ROS), CLI over USB, display. */

    vTaskStartScheduler();
    for (;;) { }
}
